#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
setxkbmap -layout pt


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config active_border_color '#1a376b'
bspc config normal_border_color '#1a376b'
bspc config focused_border_color '#5698d9'

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
bspc rule -a Zathura desktop='^8' follow=on
#bspc rule -a Discord desktop='^9' follow=on
#bspc rule -a Spotify desktop='^7' follow=on
bspc rule -a Screenkey manage=off
